### ISSUE TITLE
A doubt with the use of redirect Twig tag

### ISSUE THREAD

**Issue by informas** [helmutkaufmann/wn-twigext-plugin#1]
Hi,
in the example you say that to use redirect Twig tag we must use:

{% redirect('https://mercator.li') %}

I have tried to put it directly on a new page (for example /redir-test) and when I want to test it, I have the following error:

Unknown "redirect" tag.

but if instead of using it as in the example, I use it like this:

**Comment by helmutkaufmann** [comment]
I think you have not completed your question but you are right, the docu is not correct, please use {{ redirect("your url") }}
